# Generated by Django 2.1.5 on 2020-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_body',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
